# This rule is not used by the project vcf-salt-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to salt.vcf.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vcf-salt-operator
    app.kubernetes.io/managed-by: kustomize
  name: saltkeyconfig-viewer-role
rules:
- apiGroups:
  - salt.vcf.io
  resources:
  - saltkeyconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - salt.vcf.io
  resources:
  - saltkeyconfigs/status
  verbs:
  - get
